### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by systemsNinja** [maebert/snoo#6]
It asks for my log in, and once accepted it just clears the fields and the modal remains.
I saw a message at one point saying something not all fields are filled in or something similar

**Comment by systemsNinja** [comment]
Log Details (ERROR)
Logger: custom_components.snoo.config_flow
Source: custom_components/snoo/config_flow.py:22
First occurred: 9:34:05 PM (3 occurrences)
Last logged: 9:34:22 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/snoo/config_flow.py", line 52, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/snoo/config_flow.py", line 37, in validate_input
    fetch_token, data["username"], data["password"])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/snoo/config_flow.py", line 22, in fetch_token
    client.auth["password"] = password
  File "/usr/local/lib/python3.7/configparser.py", line 1256, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/local/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/usr/local/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/usr/local/lib/python3.7/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'kU8*%kGDHKfy%uV26*v' at position 4

**Comment by systemsNinja** [comment]
Password had an ASTERISK in it which broke the code. Changed my Password and it logged in.
