### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by ptarjan** [maebert/snoo#9]
Did they break their API?

```
$ snoo status
SNOO Username: <my email>
Password:
Traceback (most recent call last):
  File "/Users/paul.tarjan/.virtualenvs/it/bin/snoo", line 11, in <module>
    sys.exit(run())
  File "/Users/paul.tarjan/.virtualenvs/it/lib/python3.6/site-packages/snoo/__init__.py", line 34, in run
    print(client.status())
  File "/Users/paul.tarjan/.virtualenvs/it/lib/python3.6/site-packages/snoo/client.py", line 297, in status
    session = self.get_current_session()
  File "/Users/paul.tarjan/.virtualenvs/it/lib/python3.6/site-packages/snoo/client.py", line 274, in get_current_session
    level = data["levels"][-1]["level"]
IndexError: list index out of range
```

**Comment by ptarjan** [comment]
After some debugging, I do see the OAuth2 token correctly getting issued, but the API request to `/ss/v2/sessions/last` is returning
```
{'startTime': None, 'endTime': None, 'levels': []}
```

**Comment by samuelclay** [comment]
@ptarjan Small world, I was just showing somebody Webnumbr today. 

Is there any hope for this or has Happiest Baby shut down their API?
